export const googleSheetsConfig = {
  endpoint: process.env.NEXT_PUBLIC_GOOGLE_SHEETS_ENDPOINT || "",
  apiKey: process.env.GOOGLE_SHEETS_API_KEY || "",
  revalidateSeconds: 3600,
  sheets: {
    portfolioSettings: "portfolio_settings",
    projects: "projects",
    certifications: "certifications",
    achievements: "achievements",
    skills: "skills",
    socialLinks: "social_links",
  },
  columns: {
    portfolioSettings: {
      name: "name",
      headline: "headline",
      bio: "bio",
      email: "email",
      phone: "phone",
      location: "location",
      github: "github",
      linkedin: "linkedin",
      leetcode: "leetcode",
      codeforces: "codeforces",
      hackerrank: "hackerrank",
      resumeUrl: "resume_url",
      profileImage: "profile_image",
      profileBanner: "profile_banner",
      recruiterMessage: "recruiter_message",
    },
    projects: {
      slug: "slug",
      title: "title",
      summary: "summary",
      description: "description",
      problem: "problem",
      outcome: "outcome",
      githubUrl: "github_url",
      liveUrl: "live_url",
      category: "category",
      status: "status",
      techStack: "tech_stack",
      achievements: "achievements",
      imageUrl: "image_url",
      featured: "featured",
      startDate: "start_date",
      endDate: "end_date",
    },
    certifications: {
      title: "title",
      issuer: "issuer",
      issueDate: "issue_date",
      credentialId: "credential_id",
      credentialUrl: "credential_url",
      imageUrl: "image_url",
      skills: "skills",
      focus: "focus",
    },
    achievements: {
      title: "title",
      description: "description",
      organization: "organization",
      date: "date",
      imageUrl: "image_url",
    },
    skills: {
      name: "name",
      category: "category",
      proficiency: "proficiency",
      description: "description",
    },
    socialLinks: {
      label: "platform",
      href: "url",
    },
  },
};
