export const siteConfig = {
  name: "Manamoy",
  headline: "Building intelligent products with full-stack precision.",
  role: "AI Engineer | Full Stack Developer | Data Science Enthusiast",
  bio: "AI-minded full-stack developer building practical software, ML systems, and polished product experiences.",
  location: "India",
  url: process.env.NEXT_PUBLIC_SITE_URL || "http://localhost:3000",
  description:
    "A production-ready personal portfolio platform for Manamoy, an AI engineer and full-stack product builder focused on useful intelligent systems.",
  email: "hello@manamoy.dev",
  github: "https://github.com/ManamoyB",
  linkedin: "https://www.linkedin.com/in/manamoyb/",
  leetcode: "",
  codeforces: "",
  hackerrank: "",
  resumeUrl: "",
  recruiterMessage:
    "Open to thoughtful engineering opportunities, AI product work, and product-minded collaborations.",
  keywords: [
    "Manamoy",
    "AI Engineer",
    "Full Stack Developer",
    "Data Science",
    "Machine Learning",
    "Portfolio",
    "Next.js",
    "Supabase",
    "PostgreSQL",
    "Vercel",
  ],
};
